fix(generate): fix association alias duplication
ForestAdmin/lumber pull request #473
Opened 2020-09-21 15:50 UTC by arnaud-moncel

## Pull Request checklist:

- [X] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [X] Create automatic tests
- [X] No automatic tests failures
- [X] Test manually the implemented changes
- [X] Review my own code (indentation, syntax, style, simplicity, readability)
- [ ] Wonder if you can improve the existing code

2020-09-22 09:46 UTC, arnaud-moncel commented on templates/app/models/sequelize-model.hbs
> -      target: {
This option is not handled by Sequelize see the [documlentation](https://sequelize.org/master/class/lib/model.js~Model.html#static-method-belongsTo) about this.

2020-09-22 09:46 UTC, arnaud-moncel commented on services/dumper.js
> -      if (reference.targetKey) {
Not used since Sequelize doesn’t support `target` option.

2020-09-22 09:46 UTC, arnaud-moncel commented on services/analyzer/sequelize-tables-analyzer.js
> +    if (foreignKey.foreignColumnName !== 'id') {
Linked to `target` option refactoring.

2020-09-22 09:46 UTC, arnaud-moncel commented on services/analyzer/sequelize-tables-analyzer.js
> +  if (isReferenceAlreadyExist(existingsReferences, reference)) return null;
This is the fix of duplicate reference.

2020-09-22 09:46 UTC, arnaud-moncel commented on services/analyzer/sequelize-tables-analyzer.js
> +  if (isAssociationNameAlreadyExist(existingsReferences, reference)) {
This is the fix of duplicate reference alias.

2020-09-22 09:46 UTC, arnaud-moncel commented on services/analyzer/sequelize-tables-analyzer.js
> +  return isPrimary || isUnique;
This is a little refacto to reduce cognitive complexity of `createAllReferences` function.

2020-09-22 09:46 UTC, arnaud-moncel commented on services/analyzer/sequelize-tables-analyzer.js
> +function createBelongsToReference(referenceTable, tableReferences, constraint) {
This function is created to reduce cognitive complexity of `createAllReferences`.

2020-09-22 09:46 UTC, arnaud-moncel commented on services/analyzer/sequelize-tables-analyzer.js
> +  // remove null references
This piece of code is to reduce cognitive complexity of the function.

2020-09-22 09:49 UTC, arnaudbesnier commented
Task linked: [CU-88ng48 P1 - Lumber - Ensure that alias and field names are unique in a model to prevent admin backend crash on first start](https://app.clickup.com/t/88ng48)

2020-09-22 10:13 UTC, guillaumedeslandes commented on test-fixtures/mssql/doubleref.sql
> +CREATE TABLE doubleref (
```suggestion
DROP TABLE IF EXISTS doubleref;

CREATE TABLE doubleref (
```

2020-09-22 10:14 UTC, guillaumedeslandes commented on test-fixtures/mysql/doubleref.sql
> +CREATE TABLE doubleref (
```suggestion
DROP TABLE IF EXISTS doubleref;

CREATE TABLE doubleref (
```

2020-09-22 10:14 UTC, guillaumedeslandes commented on test-fixtures/postgres/doubleref.sql
> +CREATE TABLE doubleref (
```suggestion
DROP TABLE IF EXISTS doubleref;

CREATE TABLE doubleref (
```

2020-09-22 10:27 UTC, guillaumedeslandes commented on templates/app/models/sequelize-model.hbs
> +    {{/if}}
Shouldn't this `if` be indented more?

2020-09-22 10:32 UTC, guillaumedeslandes commented on services/analyzer/sequelize-tables-analyzer.js
> +  return isPrimary || isUnique;
```suggestion

  return isPrimary || isUnique;
```

2020-09-22 10:39 UTC, guillaumedeslandes commented on services/analyzer/sequelize-tables-analyzer.js
> +  return existingReferences.some((reference) => (
Not fond of these names. They combine `is` and a verb.
I'd use either
* `associationNameAlreadyExists` or `associationNameIsAlreadyDefined` or `associationNameIsAlreadyUsed`.
* `referenceAlreadyExists` or `referenceIsAlreadyDefined` or `referenceIsAlreadyUsed`

2020-09-22 15:15 UTC, guillaumedeslandes commented on services/analyzer/sequelize-tables-analyzer.js
> +    reference.ref === newReference.ref
I got a `null` value for `reference` while testing. Not sure of the reason, but worth investigating.

2020-09-22 15:16 UTC, guillaumedeslandes requested changes
See comment on `null` parameter.

2020-09-23 10:09 UTC, guillaumedeslandes approved these changes

2020-09-23 12:26 UTC, merged